import React from 'react';
import { notFound } from 'next/navigation';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ToolEngineRunner from '@/components/ToolEngineRunner';
import { TOOLS_REGISTRY, ToolMeta } from '@/data/toolsRegistry';
import { ShieldCheck, Cpu, BookOpen, ArrowRight, Zap } from 'lucide-react';
import Link from 'next/link';

export async function generateStaticParams() {
  return TOOLS_REGISTRY.map((tool) => ({
    slug: tool.slug,
  }));
}

export default function ToolPage({ params }: { params: { slug: string } }) {
  const tool = TOOLS_REGISTRY.find((t) => t.slug === params.slug);

  if (!tool) {
    notFound();
  }

  const companionTool = TOOLS_REGISTRY.find(
    (t) => t.slug === tool.companionToolSlug
  );

  const relatedTools = TOOLS_REGISTRY.filter(
    (t) => t.slug !== tool.slug
  ).slice(0, 3);

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: `Is this ${tool.name} completely free to use?`,
        acceptedAnswer: {
          '@type': 'Answer',
          text: `Yes, ${tool.name} is 100% free with no registration, no hidden usage tiers, and zero server upload latency.`,
        },
      },
      {
        '@type': 'Question',
        name: `Does ${tool.name} store or upload my files and queries?`,
        acceptedAnswer: {
          '@type': 'Answer',
          text: `No. All operations, mathematical calculations, and media processing execute strictly within your client browser RAM via WebAssembly and Canvas APIs.`,
        },
      },
      {
        '@type': 'Question',
        name: `Can I use outputs from ${tool.name} for commercial projects?`,
        acceptedAnswer: {
          '@type': 'Answer',
          text: `Yes, all compiled outputs, formatted payloads, and processed media generated by this engine are completely royalty-free for commercial use.`,
        },
      },
    ],
  };

  return (
    <div className="min-h-screen bg-zinc-50/40 text-zinc-900 selection:bg-violet-100 selection:text-violet-900 pb-20">
      <Navbar />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6">
        <nav className="flex items-center gap-2 text-xs text-zinc-500 mb-6">
          <Link href="/" className="hover:text-violet-600 transition-colors">Home</Link>
          <span>/</span>
          <span>{tool.category} Tools</span>
          <span>/</span>
          <span className="font-semibold text-zinc-900">{tool.name}</span>
        </nav>

        <ToolEngineRunner tool={tool} />

        {companionTool && (
          <section className="mt-8 rounded-2xl border border-violet-200 bg-gradient-to-r from-violet-50/80 via-white to-indigo-50/80 p-6 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="inline-flex items-center gap-1.5 text-xs font-bold text-violet-800">
                <Zap className="h-3.5 w-3.5 text-violet-600" />
                <span>Recommended Companion Workflow</span>
              </div>
              <p className="text-xs text-zinc-600 max-w-2xl leading-relaxed">
                {tool.companionPitch}
              </p>
            </div>
            <Link
              href={`/tools/${companionTool.slug}`}
              className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-violet-700 transition-all shrink-0 hover:translate-x-0.5"
            >
              <span>Launch {companionTool.name}</span>
              <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </section>
        )}

        <article className="mt-12 space-y-8 rounded-2xl border border-zinc-200/80 bg-white p-6 sm:p-10 shadow-sm text-zinc-800">
          <div className="border-b border-zinc-100 pb-6">
            <div className="flex items-center gap-2 text-xs font-semibold text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full w-fit border border-emerald-200/60 mb-3">
              <ShieldCheck className="h-3.5 w-3.5 text-emerald-600" />
              <span>Verified Client-Side Execution Standard</span>
            </div>
            <h1 className="text-2xl font-black tracking-tight sm:text-3xl text-zinc-950">
              Technical Guide: {tool.name} Architecture
            </h1>
            <p className="mt-2 text-xs sm:text-sm text-zinc-600">
              An exhaustive architectural analysis of client-side execution, algorithmic performance, and memory sandboxing.
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900 flex items-center gap-2">
              <Cpu className="h-5 w-5 text-violet-600" />
              How It Operates Under the Hood
            </h2>
            <p className="text-xs sm:text-sm leading-relaxed text-zinc-600">
              Unlike cloud utility platforms that transfer your code, image binaries, or financial variables over the internet to remote servers,
              this tool operates under a strict <strong>Zero-Server Execution Paradigm</strong>. Everything executes strictly inside your browser thread via sandboxed WebAssembly (WASM) and local Canvas allocations.
            </p>
          </section>

          <section className="space-y-3">
            <h3 className="text-sm font-bold text-zinc-900">Architecture & Performance Metrics</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border border-zinc-100">
                <thead className="bg-zinc-50 text-zinc-700 font-bold border-b border-zinc-100">
                  <tr>
                    <th className="p-3">Parameter</th>
                    <th className="p-3">Specification</th>
                    <th className="p-3">Privacy Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-100 text-zinc-600">
                  <tr>
                    <td className="p-3 font-medium text-zinc-900">Execution Sandbox</td>
                    <td className="p-3">{tool.badge}</td>
                    <td className="p-3 text-emerald-600 font-semibold">100% Client-Side Local</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium text-zinc-900">Network Latency</td>
                    <td className="p-3">0ms (Local Execution)</td>
                    <td className="p-3 text-emerald-600 font-semibold">Zero Remote Payload</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-medium text-zinc-900">Data Retention Policy</td>
                    <td className="p-3">Immediate garbage collection on tab close</td>
                    <td className="p-3 text-emerald-600 font-semibold">Zero Server Telemetry</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          <section className="space-y-4 pt-4 border-t border-zinc-100">
            <h2 className="text-lg font-bold text-zinc-900 flex items-center gap-2">
              <BookOpen className="h-5 w-5 text-violet-600" />
              Frequently Asked Questions
            </h2>
            <div className="space-y-3">
              <div className="rounded-xl border border-zinc-100 p-4 bg-zinc-50/50">
                <h4 className="text-xs font-bold text-zinc-900">Is {tool.name} free for commercial use?</h4>
                <p className="mt-1 text-xs text-zinc-600 leading-relaxed">Yes. All output files, extracted covers, and calculated growth schedules generated by this engine are completely royalty-free.</p>
              </div>
              <div className="rounded-xl border border-zinc-100 p-4 bg-zinc-50/50">
                <h4 className="text-xs font-bold text-zinc-900">Why does this tool execute faster than other online utilities?</h4>
                <p className="mt-1 text-xs text-zinc-600 leading-relaxed">Most websites serialize data over the network, queue on remote VMs, and download responses. Our client-side model computes directly inside your device RAM for instantaneous feedback.</p>
              </div>
            </div>
          </section>
        </article>

        <section className="mt-12">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-bold text-zinc-900">Explore Other Utilities</h3>
            <Link href="/#tools" className="text-xs font-semibold text-violet-600 hover:underline">View All 80 Tools →</Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {relatedTools.map((relTool: ToolMeta) => (
              <Link key={relTool.slug} href={`/tools/${relTool.slug}`} className="group rounded-xl border border-zinc-200 bg-white p-4 shadow-sm hover:border-violet-300 hover:shadow-md transition-all text-left">
                <span className="text-[10px] font-semibold text-violet-700 bg-violet-50 px-2 py-0.5 rounded">{relTool.category}</span>
                <h4 className="mt-2 text-xs font-bold text-zinc-900 group-hover:text-violet-600 transition-colors">{relTool.name}</h4>
                <p className="mt-1 text-[11px] text-zinc-500 line-clamp-2 leading-relaxed">{relTool.description}</p>
              </Link>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
